[package]
name = "typeswitch"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.0", features = ["secrets", "tls"] }
rocket_dyn_templates = { version = "0.1.0", features = ["handlebars"] }
